apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-{{ .Values.pr.number }}
  labels:
    app: {{ .Values.service.name }}
    pr: "{{ .Values.pr.number }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
      pr: "{{ .Values.pr.number }}"
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        pr: "{{ .Values.pr.number }}"
    spec:
      serviceAccountName: bookinfo-{{ .Values.service.name }}
      containers:
      - name: {{ .Values.service.name }}
        image: {{ .Values.container.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
