apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Values.pr.number }}
  labels:
    app: {{ .Values.service.name }}
    pr: "{{ .Values.pr.number }}"
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: {{ .Values.service.name }}
    pr: "{{ .Values.pr.number }}"
